title: x86trace
markdown: kramdown

# for atom feed
author:
  name: trace
  email:

timezone: Asia/Kolkata

safe: true

plugins:
  - jemoji

kramdown:
  parse_block_html: true

whitelist:
  - jemoji

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
