baseURL: www.leonnunes.dev
languageCode: en-us
title: Leon's Personal Void
theme: PaperMod

menu:
  main:
    - identifier: content
      name: Blog
      url: /posts
    - identifier: Dev.to
      name: Dev.to
      url: https://dev.to/mediocreDevops
    - identifier: Hashnode
      name: Hashnode
      url: https://blog.mediocredevops.com

params:
    profileMode:
        enabled: true
        title: "You've Successfully landed 🚀" # optional default will be site title
        subtitle: "Tinkerer, Doesn't fit in"
        imageUrl: "profile.png" # optional
        imageTitle: "Profile picture" # optional
        imageWidth: 200 # custom size
        imageHeight: 237 # custom size
        buttons:
            - name: Github
              url: "https://github.com/afro-coder"
    socialIcons: # optional
        - name: "Twitter"
          url: "https://twitter.com/mediocreDevops"
        - name: "Twitch"
          url: "https://twitch.tv/leon_nunes"
        - name: "Linkedin"
          url: "https://linkedin.com/in/leon-nunes"
