name: "github-pages-blog"

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.70.0'
          extended: true
      
      - name: Build Site
        run: hugo --minify
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
          user_name: 'shantanoo-desai-blog-bot'
          user_email: 'shantanoo-desai-blog-bot@users.noreply.github.com'
          commit_message: 'Deploy: Update Blog Content'
          external_repository: 'shantanoo-desai/shantanoo-desai.github.io'
          publish_branch: 'master'
